// Code generated by go-swagger; DO NOT EDIT.

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRbacPermissionsByNameGetParams creates a new RbacPermissionsByNameGetParams object
// with the default values initialized.
func NewRbacPermissionsByNameGetParams() *RbacPermissionsByNameGetParams {
	var ()
	return &RbacPermissionsByNameGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRbacPermissionsByNameGetParamsWithTimeout creates a new RbacPermissionsByNameGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRbacPermissionsByNameGetParamsWithTimeout(timeout time.Duration) *RbacPermissionsByNameGetParams {
	var ()
	return &RbacPermissionsByNameGetParams{

		timeout: timeout,
	}
}

// NewRbacPermissionsByNameGetParamsWithContext creates a new RbacPermissionsByNameGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewRbacPermissionsByNameGetParamsWithContext(ctx context.Context) *RbacPermissionsByNameGetParams {
	var ()
	return &RbacPermissionsByNameGetParams{

		Context: ctx,
	}
}

// NewRbacPermissionsByNameGetParamsWithHTTPClient creates a new RbacPermissionsByNameGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRbacPermissionsByNameGetParamsWithHTTPClient(client *http.Client) *RbacPermissionsByNameGetParams {
	var ()
	return &RbacPermissionsByNameGetParams{
		HTTPClient: client,
	}
}

/*RbacPermissionsByNameGetParams contains all the parameters to send to the API endpoint
for the rbac permissions by name get operation typically these are written to a http.Request
*/
type RbacPermissionsByNameGetParams struct {

	/*Name
	  Permission Name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) WithTimeout(timeout time.Duration) *RbacPermissionsByNameGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) WithContext(ctx context.Context) *RbacPermissionsByNameGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) WithHTTPClient(client *http.Client) *RbacPermissionsByNameGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) WithName(name string) *RbacPermissionsByNameGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the rbac permissions by name get params
func (o *RbacPermissionsByNameGetParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *RbacPermissionsByNameGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
