// Code generated by go-swagger; DO NOT EDIT.

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// RbacRolesByNameGetReader is a Reader for the RbacRolesByNameGet structure.
type RbacRolesByNameGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RbacRolesByNameGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRbacRolesByNameGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRbacRolesByNameGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRbacRolesByNameGetOK creates a RbacRolesByNameGetOK with default headers values
func NewRbacRolesByNameGetOK() *RbacRolesByNameGetOK {
	return &RbacRolesByNameGetOK{}
}

/*RbacRolesByNameGetOK handles this case with default header values.

Role info
*/
type RbacRolesByNameGetOK struct {
	Payload *models.RoleDesc
}

func (o *RbacRolesByNameGetOK) Error() string {
	return fmt.Sprintf("[GET /rbac/roles/{name}][%d] rbacRolesByNameGetOK  %+v", 200, o.Payload)
}

func (o *RbacRolesByNameGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleDesc)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRbacRolesByNameGetDefault creates a RbacRolesByNameGetDefault with default headers values
func NewRbacRolesByNameGetDefault(code int) *RbacRolesByNameGetDefault {
	return &RbacRolesByNameGetDefault{
		_statusCode: code,
	}
}

/*RbacRolesByNameGetDefault handles this case with default header values.

Error response
*/
type RbacRolesByNameGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the rbac roles by name get default response
func (o *RbacRolesByNameGetDefault) Code() int {
	return o._statusCode
}

func (o *RbacRolesByNameGetDefault) Error() string {
	return fmt.Sprintf("[GET /rbac/roles/{name}][%d] RbacRolesByNameGet default  %+v", o._statusCode, o.Payload)
}

func (o *RbacRolesByNameGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
