// Code generated by go-swagger; DO NOT EDIT.

package rbac

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// RbacRolesGetReader is a Reader for the RbacRolesGet structure.
type RbacRolesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RbacRolesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewRbacRolesGetNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRbacRolesGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRbacRolesGetNoContent creates a RbacRolesGetNoContent with default headers values
func NewRbacRolesGetNoContent() *RbacRolesGetNoContent {
	return &RbacRolesGetNoContent{}
}

/*RbacRolesGetNoContent handles this case with default header values.

Roles list
*/
type RbacRolesGetNoContent struct {
	Payload []*models.RoleDesc
}

func (o *RbacRolesGetNoContent) Error() string {
	return fmt.Sprintf("[GET /rbac/roles/][%d] rbacRolesGetNoContent  %+v", 204, o.Payload)
}

func (o *RbacRolesGetNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRbacRolesGetDefault creates a RbacRolesGetDefault with default headers values
func NewRbacRolesGetDefault(code int) *RbacRolesGetDefault {
	return &RbacRolesGetDefault{
		_statusCode: code,
	}
}

/*RbacRolesGetDefault handles this case with default header values.

Error response
*/
type RbacRolesGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the rbac roles get default response
func (o *RbacRolesGetDefault) Code() int {
	return o._statusCode
}

func (o *RbacRolesGetDefault) Error() string {
	return fmt.Sprintf("[GET /rbac/roles/][%d] RbacRolesGet default  %+v", o._statusCode, o.Payload)
}

func (o *RbacRolesGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
