// Code generated by go-swagger; DO NOT EDIT.

package operational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMetricsGetParams creates a new MetricsGetParams object
// with the default values initialized.
func NewMetricsGetParams() *MetricsGetParams {

	return &MetricsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMetricsGetParamsWithTimeout creates a new MetricsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMetricsGetParamsWithTimeout(timeout time.Duration) *MetricsGetParams {

	return &MetricsGetParams{

		timeout: timeout,
	}
}

// NewMetricsGetParamsWithContext creates a new MetricsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewMetricsGetParamsWithContext(ctx context.Context) *MetricsGetParams {

	return &MetricsGetParams{

		Context: ctx,
	}
}

// NewMetricsGetParamsWithHTTPClient creates a new MetricsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMetricsGetParamsWithHTTPClient(client *http.Client) *MetricsGetParams {

	return &MetricsGetParams{
		HTTPClient: client,
	}
}

/*MetricsGetParams contains all the parameters to send to the API endpoint
for the metrics get operation typically these are written to a http.Request
*/
type MetricsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the metrics get params
func (o *MetricsGetParams) WithTimeout(timeout time.Duration) *MetricsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the metrics get params
func (o *MetricsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the metrics get params
func (o *MetricsGetParams) WithContext(ctx context.Context) *MetricsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the metrics get params
func (o *MetricsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the metrics get params
func (o *MetricsGetParams) WithHTTPClient(client *http.Client) *MetricsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the metrics get params
func (o *MetricsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MetricsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
