// Code generated by go-swagger; DO NOT EDIT.

package operational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operational API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operational API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
MetricsGet gets metrics

Prometheus metrics
*/
func (a *Client) MetricsGet(params *MetricsGetParams) (*MetricsGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewMetricsGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "MetricsGet",
		Method:             "GET",
		PathPattern:        "/metrics",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &MetricsGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*MetricsGetOK), nil

}

/*
VersionGet gets version

Version info
*/
func (a *Client) VersionGet(params *VersionGetParams) (*VersionGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "VersionGet",
		Method:             "GET",
		PathPattern:        "/version",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VersionGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*VersionGetOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
