// Code generated by go-swagger; DO NOT EDIT.

package operational

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// VersionGetReader is a Reader for the VersionGet structure.
type VersionGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVersionGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVersionGetOK creates a VersionGetOK with default headers values
func NewVersionGetOK() *VersionGetOK {
	return &VersionGetOK{}
}

/*VersionGetOK handles this case with default header values.

Version info
*/
type VersionGetOK struct {
	Payload *models.VersionResponse
}

func (o *VersionGetOK) Error() string {
	return fmt.Sprintf("[GET /version][%d] versionGetOK  %+v", 200, o.Payload)
}

func (o *VersionGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
