// Code generated by go-swagger; DO NOT EDIT.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMembersUserByMemberIDGetParams creates a new MembersUserByMemberIDGetParams object
// with the default values initialized.
func NewMembersUserByMemberIDGetParams() *MembersUserByMemberIDGetParams {
	var ()
	return &MembersUserByMemberIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMembersUserByMemberIDGetParamsWithTimeout creates a new MembersUserByMemberIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMembersUserByMemberIDGetParamsWithTimeout(timeout time.Duration) *MembersUserByMemberIDGetParams {
	var ()
	return &MembersUserByMemberIDGetParams{

		timeout: timeout,
	}
}

// NewMembersUserByMemberIDGetParamsWithContext creates a new MembersUserByMemberIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewMembersUserByMemberIDGetParamsWithContext(ctx context.Context) *MembersUserByMemberIDGetParams {
	var ()
	return &MembersUserByMemberIDGetParams{

		Context: ctx,
	}
}

// NewMembersUserByMemberIDGetParamsWithHTTPClient creates a new MembersUserByMemberIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMembersUserByMemberIDGetParamsWithHTTPClient(client *http.Client) *MembersUserByMemberIDGetParams {
	var ()
	return &MembersUserByMemberIDGetParams{
		HTTPClient: client,
	}
}

/*MembersUserByMemberIDGetParams contains all the parameters to send to the API endpoint
for the members user by member Id get operation typically these are written to a http.Request
*/
type MembersUserByMemberIDGetParams struct {

	/*MemberID*/
	MemberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) WithTimeout(timeout time.Duration) *MembersUserByMemberIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) WithContext(ctx context.Context) *MembersUserByMemberIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) WithHTTPClient(client *http.Client) *MembersUserByMemberIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMemberID adds the memberID to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) WithMemberID(memberID string) *MembersUserByMemberIDGetParams {
	o.SetMemberID(memberID)
	return o
}

// SetMemberID adds the memberId to the members user by member Id get params
func (o *MembersUserByMemberIDGetParams) SetMemberID(memberID string) {
	o.MemberID = memberID
}

// WriteToRequest writes these params to a swagger request
func (o *MembersUserByMemberIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param memberId
	if err := r.SetPathParam("memberId", o.MemberID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
