// Code generated by go-swagger; DO NOT EDIT.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// MembersUserByMemberIDGetReader is a Reader for the MembersUserByMemberIDGet structure.
type MembersUserByMemberIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MembersUserByMemberIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMembersUserByMemberIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMembersUserByMemberIDGetOK creates a MembersUserByMemberIDGetOK with default headers values
func NewMembersUserByMemberIDGetOK() *MembersUserByMemberIDGetOK {
	return &MembersUserByMemberIDGetOK{}
}

/*MembersUserByMemberIDGetOK handles this case with default header values.

List all members response
*/
type MembersUserByMemberIDGetOK struct {
	Payload *models.User
}

func (o *MembersUserByMemberIDGetOK) Error() string {
	return fmt.Sprintf("[GET /members/{memberId}/user][%d] membersUserByMemberIdGetOK  %+v", 200, o.Payload)
}

func (o *MembersUserByMemberIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
