// Code generated by go-swagger; DO NOT EDIT.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// TenantsMembersByIDGetReader is a Reader for the TenantsMembersByIDGet structure.
type TenantsMembersByIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantsMembersByIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTenantsMembersByIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTenantsMembersByIDGetOK creates a TenantsMembersByIDGetOK with default headers values
func NewTenantsMembersByIDGetOK() *TenantsMembersByIDGetOK {
	return &TenantsMembersByIDGetOK{}
}

/*TenantsMembersByIDGetOK handles this case with default header values.

List all members response
*/
type TenantsMembersByIDGetOK struct {
	Payload *models.TenantsMembersResponse
}

func (o *TenantsMembersByIDGetOK) Error() string {
	return fmt.Sprintf("[GET /tenants/{id}/members/][%d] tenantsMembersByIdGetOK  %+v", 200, o.Payload)
}

func (o *TenantsMembersByIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantsMembersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
