// Code generated by go-swagger; DO NOT EDIT.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTenantsMembersByIDGetParams creates a new TenantsMembersByIDGetParams object
// with the default values initialized.
func NewTenantsMembersByIDGetParams() *TenantsMembersByIDGetParams {
	var ()
	return &TenantsMembersByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTenantsMembersByIDGetParamsWithTimeout creates a new TenantsMembersByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTenantsMembersByIDGetParamsWithTimeout(timeout time.Duration) *TenantsMembersByIDGetParams {
	var ()
	return &TenantsMembersByIDGetParams{

		timeout: timeout,
	}
}

// NewTenantsMembersByIDGetParamsWithContext creates a new TenantsMembersByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewTenantsMembersByIDGetParamsWithContext(ctx context.Context) *TenantsMembersByIDGetParams {
	var ()
	return &TenantsMembersByIDGetParams{

		Context: ctx,
	}
}

// NewTenantsMembersByIDGetParamsWithHTTPClient creates a new TenantsMembersByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTenantsMembersByIDGetParamsWithHTTPClient(client *http.Client) *TenantsMembersByIDGetParams {
	var ()
	return &TenantsMembersByIDGetParams{
		HTTPClient: client,
	}
}

/*TenantsMembersByIDGetParams contains all the parameters to send to the API endpoint
for the tenants members by Id get operation typically these are written to a http.Request
*/
type TenantsMembersByIDGetParams struct {

	/*ID
	  User ID

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) WithTimeout(timeout time.Duration) *TenantsMembersByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) WithContext(ctx context.Context) *TenantsMembersByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) WithHTTPClient(client *http.Client) *TenantsMembersByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) WithID(id strfmt.UUID) *TenantsMembersByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the tenants members by Id get params
func (o *TenantsMembersByIDGetParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *TenantsMembersByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
