// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// EmailUpdatePostReader is a Reader for the EmailUpdatePost structure.
type EmailUpdatePostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmailUpdatePostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewEmailUpdatePostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEmailUpdatePostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEmailUpdatePostNoContent creates a EmailUpdatePostNoContent with default headers values
func NewEmailUpdatePostNoContent() *EmailUpdatePostNoContent {
	return &EmailUpdatePostNoContent{}
}

/*EmailUpdatePostNoContent handles this case with default header values.

Empty response
*/
type EmailUpdatePostNoContent struct {
}

func (o *EmailUpdatePostNoContent) Error() string {
	return fmt.Sprintf("[POST /email_update][%d] emailUpdatePostNoContent ", 204)
}

func (o *EmailUpdatePostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEmailUpdatePostDefault creates a EmailUpdatePostDefault with default headers values
func NewEmailUpdatePostDefault(code int) *EmailUpdatePostDefault {
	return &EmailUpdatePostDefault{
		_statusCode: code,
	}
}

/*EmailUpdatePostDefault handles this case with default header values.

Error response
*/
type EmailUpdatePostDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the email update post default response
func (o *EmailUpdatePostDefault) Code() int {
	return o._statusCode
}

func (o *EmailUpdatePostDefault) Error() string {
	return fmt.Sprintf("[POST /email_update][%d] EmailUpdatePost default  %+v", o._statusCode, o.Payload)
}

func (o *EmailUpdatePostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
