// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// NewEmailUpdatePostParams creates a new EmailUpdatePostParams object
// with the default values initialized.
func NewEmailUpdatePostParams() *EmailUpdatePostParams {
	var ()
	return &EmailUpdatePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmailUpdatePostParamsWithTimeout creates a new EmailUpdatePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmailUpdatePostParamsWithTimeout(timeout time.Duration) *EmailUpdatePostParams {
	var ()
	return &EmailUpdatePostParams{

		timeout: timeout,
	}
}

// NewEmailUpdatePostParamsWithContext creates a new EmailUpdatePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmailUpdatePostParamsWithContext(ctx context.Context) *EmailUpdatePostParams {
	var ()
	return &EmailUpdatePostParams{

		Context: ctx,
	}
}

// NewEmailUpdatePostParamsWithHTTPClient creates a new EmailUpdatePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmailUpdatePostParamsWithHTTPClient(client *http.Client) *EmailUpdatePostParams {
	var ()
	return &EmailUpdatePostParams{
		HTTPClient: client,
	}
}

/*EmailUpdatePostParams contains all the parameters to send to the API endpoint
for the email update post operation typically these are written to a http.Request
*/
type EmailUpdatePostParams struct {

	/*Body*/
	Body *models.EmailUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the email update post params
func (o *EmailUpdatePostParams) WithTimeout(timeout time.Duration) *EmailUpdatePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the email update post params
func (o *EmailUpdatePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the email update post params
func (o *EmailUpdatePostParams) WithContext(ctx context.Context) *EmailUpdatePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the email update post params
func (o *EmailUpdatePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the email update post params
func (o *EmailUpdatePostParams) WithHTTPClient(client *http.Client) *EmailUpdatePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the email update post params
func (o *EmailUpdatePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the email update post params
func (o *EmailUpdatePostParams) WithBody(body *models.EmailUpdateRequest) *EmailUpdatePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the email update post params
func (o *EmailUpdatePostParams) SetBody(body *models.EmailUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EmailUpdatePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
