// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// PasswordResetPostReader is a Reader for the PasswordResetPost structure.
type PasswordResetPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PasswordResetPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPasswordResetPostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPasswordResetPostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPasswordResetPostNoContent creates a PasswordResetPostNoContent with default headers values
func NewPasswordResetPostNoContent() *PasswordResetPostNoContent {
	return &PasswordResetPostNoContent{}
}

/*PasswordResetPostNoContent handles this case with default header values.

Empty response
*/
type PasswordResetPostNoContent struct {
}

func (o *PasswordResetPostNoContent) Error() string {
	return fmt.Sprintf("[POST /password_reset][%d] passwordResetPostNoContent ", 204)
}

func (o *PasswordResetPostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPasswordResetPostDefault creates a PasswordResetPostDefault with default headers values
func NewPasswordResetPostDefault(code int) *PasswordResetPostDefault {
	return &PasswordResetPostDefault{
		_statusCode: code,
	}
}

/*PasswordResetPostDefault handles this case with default header values.

Error response
*/
type PasswordResetPostDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the password reset post default response
func (o *PasswordResetPostDefault) Code() int {
	return o._statusCode
}

func (o *PasswordResetPostDefault) Error() string {
	return fmt.Sprintf("[POST /password_reset][%d] PasswordResetPost default  %+v", o._statusCode, o.Payload)
}

func (o *PasswordResetPostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
