// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// NewRequestPasswordResetPostParams creates a new RequestPasswordResetPostParams object
// with the default values initialized.
func NewRequestPasswordResetPostParams() *RequestPasswordResetPostParams {
	var ()
	return &RequestPasswordResetPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestPasswordResetPostParamsWithTimeout creates a new RequestPasswordResetPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestPasswordResetPostParamsWithTimeout(timeout time.Duration) *RequestPasswordResetPostParams {
	var ()
	return &RequestPasswordResetPostParams{

		timeout: timeout,
	}
}

// NewRequestPasswordResetPostParamsWithContext creates a new RequestPasswordResetPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestPasswordResetPostParamsWithContext(ctx context.Context) *RequestPasswordResetPostParams {
	var ()
	return &RequestPasswordResetPostParams{

		Context: ctx,
	}
}

// NewRequestPasswordResetPostParamsWithHTTPClient creates a new RequestPasswordResetPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestPasswordResetPostParamsWithHTTPClient(client *http.Client) *RequestPasswordResetPostParams {
	var ()
	return &RequestPasswordResetPostParams{
		HTTPClient: client,
	}
}

/*RequestPasswordResetPostParams contains all the parameters to send to the API endpoint
for the request password reset post operation typically these are written to a http.Request
*/
type RequestPasswordResetPostParams struct {

	/*Body
	  User's email

	*/
	Body *models.RequestPasswordResetRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request password reset post params
func (o *RequestPasswordResetPostParams) WithTimeout(timeout time.Duration) *RequestPasswordResetPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request password reset post params
func (o *RequestPasswordResetPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request password reset post params
func (o *RequestPasswordResetPostParams) WithContext(ctx context.Context) *RequestPasswordResetPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request password reset post params
func (o *RequestPasswordResetPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request password reset post params
func (o *RequestPasswordResetPostParams) WithHTTPClient(client *http.Client) *RequestPasswordResetPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request password reset post params
func (o *RequestPasswordResetPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the request password reset post params
func (o *RequestPasswordResetPostParams) WithBody(body *models.RequestPasswordResetRequest) *RequestPasswordResetPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the request password reset post params
func (o *RequestPasswordResetPostParams) SetBody(body *models.RequestPasswordResetRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RequestPasswordResetPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
