// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// NewRequestEmailUpdatePostParams creates a new RequestEmailUpdatePostParams object
// with the default values initialized.
func NewRequestEmailUpdatePostParams() *RequestEmailUpdatePostParams {
	var ()
	return &RequestEmailUpdatePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestEmailUpdatePostParamsWithTimeout creates a new RequestEmailUpdatePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestEmailUpdatePostParamsWithTimeout(timeout time.Duration) *RequestEmailUpdatePostParams {
	var ()
	return &RequestEmailUpdatePostParams{

		timeout: timeout,
	}
}

// NewRequestEmailUpdatePostParamsWithContext creates a new RequestEmailUpdatePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestEmailUpdatePostParamsWithContext(ctx context.Context) *RequestEmailUpdatePostParams {
	var ()
	return &RequestEmailUpdatePostParams{

		Context: ctx,
	}
}

// NewRequestEmailUpdatePostParamsWithHTTPClient creates a new RequestEmailUpdatePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestEmailUpdatePostParamsWithHTTPClient(client *http.Client) *RequestEmailUpdatePostParams {
	var ()
	return &RequestEmailUpdatePostParams{
		HTTPClient: client,
	}
}

/*RequestEmailUpdatePostParams contains all the parameters to send to the API endpoint
for the request email update post operation typically these are written to a http.Request
*/
type RequestEmailUpdatePostParams struct {

	/*Body*/
	Body *models.RequestEmailUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request email update post params
func (o *RequestEmailUpdatePostParams) WithTimeout(timeout time.Duration) *RequestEmailUpdatePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request email update post params
func (o *RequestEmailUpdatePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request email update post params
func (o *RequestEmailUpdatePostParams) WithContext(ctx context.Context) *RequestEmailUpdatePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request email update post params
func (o *RequestEmailUpdatePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request email update post params
func (o *RequestEmailUpdatePostParams) WithHTTPClient(client *http.Client) *RequestEmailUpdatePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request email update post params
func (o *RequestEmailUpdatePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the request email update post params
func (o *RequestEmailUpdatePostParams) WithBody(body *models.RequestEmailUpdateRequest) *RequestEmailUpdatePostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the request email update post params
func (o *RequestEmailUpdatePostParams) SetBody(body *models.RequestEmailUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RequestEmailUpdatePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
