// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRequestPasswordResetGetParams creates a new RequestPasswordResetGetParams object
// with the default values initialized.
func NewRequestPasswordResetGetParams() *RequestPasswordResetGetParams {
	var ()
	return &RequestPasswordResetGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestPasswordResetGetParamsWithTimeout creates a new RequestPasswordResetGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestPasswordResetGetParamsWithTimeout(timeout time.Duration) *RequestPasswordResetGetParams {
	var ()
	return &RequestPasswordResetGetParams{

		timeout: timeout,
	}
}

// NewRequestPasswordResetGetParamsWithContext creates a new RequestPasswordResetGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestPasswordResetGetParamsWithContext(ctx context.Context) *RequestPasswordResetGetParams {
	var ()
	return &RequestPasswordResetGetParams{

		Context: ctx,
	}
}

// NewRequestPasswordResetGetParamsWithHTTPClient creates a new RequestPasswordResetGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestPasswordResetGetParamsWithHTTPClient(client *http.Client) *RequestPasswordResetGetParams {
	var ()
	return &RequestPasswordResetGetParams{
		HTTPClient: client,
	}
}

/*RequestPasswordResetGetParams contains all the parameters to send to the API endpoint
for the request password reset get operation typically these are written to a http.Request
*/
type RequestPasswordResetGetParams struct {

	/*Email
	  User's email address

	*/
	Email string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request password reset get params
func (o *RequestPasswordResetGetParams) WithTimeout(timeout time.Duration) *RequestPasswordResetGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request password reset get params
func (o *RequestPasswordResetGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request password reset get params
func (o *RequestPasswordResetGetParams) WithContext(ctx context.Context) *RequestPasswordResetGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request password reset get params
func (o *RequestPasswordResetGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request password reset get params
func (o *RequestPasswordResetGetParams) WithHTTPClient(client *http.Client) *RequestPasswordResetGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request password reset get params
func (o *RequestPasswordResetGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the request password reset get params
func (o *RequestPasswordResetGetParams) WithEmail(email string) *RequestPasswordResetGetParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the request password reset get params
func (o *RequestPasswordResetGetParams) SetEmail(email string) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *RequestPasswordResetGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {
		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
