// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUsersByIDGetParams creates a new UsersByIDGetParams object
// with the default values initialized.
func NewUsersByIDGetParams() *UsersByIDGetParams {
	var ()
	return &UsersByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersByIDGetParamsWithTimeout creates a new UsersByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersByIDGetParamsWithTimeout(timeout time.Duration) *UsersByIDGetParams {
	var ()
	return &UsersByIDGetParams{

		timeout: timeout,
	}
}

// NewUsersByIDGetParamsWithContext creates a new UsersByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersByIDGetParamsWithContext(ctx context.Context) *UsersByIDGetParams {
	var ()
	return &UsersByIDGetParams{

		Context: ctx,
	}
}

// NewUsersByIDGetParamsWithHTTPClient creates a new UsersByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersByIDGetParamsWithHTTPClient(client *http.Client) *UsersByIDGetParams {
	var ()
	return &UsersByIDGetParams{
		HTTPClient: client,
	}
}

/*UsersByIDGetParams contains all the parameters to send to the API endpoint
for the users by Id get operation typically these are written to a http.Request
*/
type UsersByIDGetParams struct {

	/*ID
	  User ID

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users by Id get params
func (o *UsersByIDGetParams) WithTimeout(timeout time.Duration) *UsersByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users by Id get params
func (o *UsersByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users by Id get params
func (o *UsersByIDGetParams) WithContext(ctx context.Context) *UsersByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users by Id get params
func (o *UsersByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users by Id get params
func (o *UsersByIDGetParams) WithHTTPClient(client *http.Client) *UsersByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users by Id get params
func (o *UsersByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the users by Id get params
func (o *UsersByIDGetParams) WithID(id strfmt.UUID) *UsersByIDGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the users by Id get params
func (o *UsersByIDGetParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UsersByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
