// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// UsersByIDDeleteReader is a Reader for the UsersByIDDelete structure.
type UsersByIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersByIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewUsersByIDDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUsersByIDDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUsersByIDDeleteNoContent creates a UsersByIDDeleteNoContent with default headers values
func NewUsersByIDDeleteNoContent() *UsersByIDDeleteNoContent {
	return &UsersByIDDeleteNoContent{}
}

/*UsersByIDDeleteNoContent handles this case with default header values.

Success
*/
type UsersByIDDeleteNoContent struct {
}

func (o *UsersByIDDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] usersByIdDeleteNoContent ", 204)
}

func (o *UsersByIDDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUsersByIDDeleteDefault creates a UsersByIDDeleteDefault with default headers values
func NewUsersByIDDeleteDefault(code int) *UsersByIDDeleteDefault {
	return &UsersByIDDeleteDefault{
		_statusCode: code,
	}
}

/*UsersByIDDeleteDefault handles this case with default header values.

Error response
*/
type UsersByIDDeleteDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the users by Id delete default response
func (o *UsersByIDDeleteDefault) Code() int {
	return o._statusCode
}

func (o *UsersByIDDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] UsersByIdDelete default  %+v", o._statusCode, o.Payload)
}

func (o *UsersByIDDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
