// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// NewUsersPostParams creates a new UsersPostParams object
// with the default values initialized.
func NewUsersPostParams() *UsersPostParams {
	var ()
	return &UsersPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersPostParamsWithTimeout creates a new UsersPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersPostParamsWithTimeout(timeout time.Duration) *UsersPostParams {
	var ()
	return &UsersPostParams{

		timeout: timeout,
	}
}

// NewUsersPostParamsWithContext creates a new UsersPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersPostParamsWithContext(ctx context.Context) *UsersPostParams {
	var ()
	return &UsersPostParams{

		Context: ctx,
	}
}

// NewUsersPostParamsWithHTTPClient creates a new UsersPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersPostParamsWithHTTPClient(client *http.Client) *UsersPostParams {
	var ()
	return &UsersPostParams{
		HTTPClient: client,
	}
}

/*UsersPostParams contains all the parameters to send to the API endpoint
for the users post operation typically these are written to a http.Request
*/
type UsersPostParams struct {

	/*Body
	  User info

	*/
	Body *models.UsersRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users post params
func (o *UsersPostParams) WithTimeout(timeout time.Duration) *UsersPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users post params
func (o *UsersPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users post params
func (o *UsersPostParams) WithContext(ctx context.Context) *UsersPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users post params
func (o *UsersPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users post params
func (o *UsersPostParams) WithHTTPClient(client *http.Client) *UsersPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users post params
func (o *UsersPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the users post params
func (o *UsersPostParams) WithBody(body *models.UsersRequest) *UsersPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the users post params
func (o *UsersPostParams) SetBody(body *models.UsersRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UsersPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
