// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// NewUsersByIDPatchParams creates a new UsersByIDPatchParams object
// with the default values initialized.
func NewUsersByIDPatchParams() *UsersByIDPatchParams {
	var ()
	return &UsersByIDPatchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersByIDPatchParamsWithTimeout creates a new UsersByIDPatchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersByIDPatchParamsWithTimeout(timeout time.Duration) *UsersByIDPatchParams {
	var ()
	return &UsersByIDPatchParams{

		timeout: timeout,
	}
}

// NewUsersByIDPatchParamsWithContext creates a new UsersByIDPatchParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersByIDPatchParamsWithContext(ctx context.Context) *UsersByIDPatchParams {
	var ()
	return &UsersByIDPatchParams{

		Context: ctx,
	}
}

// NewUsersByIDPatchParamsWithHTTPClient creates a new UsersByIDPatchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersByIDPatchParamsWithHTTPClient(client *http.Client) *UsersByIDPatchParams {
	var ()
	return &UsersByIDPatchParams{
		HTTPClient: client,
	}
}

/*UsersByIDPatchParams contains all the parameters to send to the API endpoint
for the users by Id patch operation typically these are written to a http.Request
*/
type UsersByIDPatchParams struct {

	/*Body
	  User's properties change list

	*/
	Body []*models.JSONPatch
	/*ID
	  User ID

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users by Id patch params
func (o *UsersByIDPatchParams) WithTimeout(timeout time.Duration) *UsersByIDPatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users by Id patch params
func (o *UsersByIDPatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users by Id patch params
func (o *UsersByIDPatchParams) WithContext(ctx context.Context) *UsersByIDPatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users by Id patch params
func (o *UsersByIDPatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users by Id patch params
func (o *UsersByIDPatchParams) WithHTTPClient(client *http.Client) *UsersByIDPatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users by Id patch params
func (o *UsersByIDPatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the users by Id patch params
func (o *UsersByIDPatchParams) WithBody(body []*models.JSONPatch) *UsersByIDPatchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the users by Id patch params
func (o *UsersByIDPatchParams) SetBody(body []*models.JSONPatch) {
	o.Body = body
}

// WithID adds the id to the users by Id patch params
func (o *UsersByIDPatchParams) WithID(id strfmt.UUID) *UsersByIDPatchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the users by Id patch params
func (o *UsersByIDPatchParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UsersByIDPatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
