// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new auth API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for auth API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
LoginGet gets login

Authenticate client using Basic scheme and return JWT token
*/
func (a *Client) LoginGet(params *LoginGetParams) (*LoginGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLoginGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "LoginGet",
		Method:             "GET",
		PathPattern:        "/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LoginGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*LoginGetOK), nil

}

/*
LoginPost posts login

Authenticate client and return JWT token
*/
func (a *Client) LoginPost(params *LoginPostParams) (*LoginPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLoginPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "LoginPost",
		Method:             "POST",
		PathPattern:        "/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LoginPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*LoginPostOK), nil

}

/*
RefreshGet refrests token

Refresh JWT token
*/
func (a *Client) RefreshGet(params *RefreshGetParams) (*RefreshGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRefreshGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "RefreshGet",
		Method:             "GET",
		PathPattern:        "/refresh",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RefreshGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RefreshGetOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
