// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// NewLoginPostParams creates a new LoginPostParams object
// with the default values initialized.
func NewLoginPostParams() *LoginPostParams {
	var ()
	return &LoginPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoginPostParamsWithTimeout creates a new LoginPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoginPostParamsWithTimeout(timeout time.Duration) *LoginPostParams {
	var ()
	return &LoginPostParams{

		timeout: timeout,
	}
}

// NewLoginPostParamsWithContext creates a new LoginPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoginPostParamsWithContext(ctx context.Context) *LoginPostParams {
	var ()
	return &LoginPostParams{

		Context: ctx,
	}
}

// NewLoginPostParamsWithHTTPClient creates a new LoginPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoginPostParamsWithHTTPClient(client *http.Client) *LoginPostParams {
	var ()
	return &LoginPostParams{
		HTTPClient: client,
	}
}

/*LoginPostParams contains all the parameters to send to the API endpoint
for the login post operation typically these are written to a http.Request
*/
type LoginPostParams struct {

	/*Body
	  User's credentials

	*/
	Body *models.LoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the login post params
func (o *LoginPostParams) WithTimeout(timeout time.Duration) *LoginPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login post params
func (o *LoginPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login post params
func (o *LoginPostParams) WithContext(ctx context.Context) *LoginPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login post params
func (o *LoginPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login post params
func (o *LoginPostParams) WithHTTPClient(client *http.Client) *LoginPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login post params
func (o *LoginPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the login post params
func (o *LoginPostParams) WithBody(body *models.LoginRequest) *LoginPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the login post params
func (o *LoginPostParams) SetBody(body *models.LoginRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *LoginPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
