// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoginGetParams creates a new LoginGetParams object
// with the default values initialized.
func NewLoginGetParams() *LoginGetParams {

	return &LoginGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoginGetParamsWithTimeout creates a new LoginGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoginGetParamsWithTimeout(timeout time.Duration) *LoginGetParams {

	return &LoginGetParams{

		timeout: timeout,
	}
}

// NewLoginGetParamsWithContext creates a new LoginGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoginGetParamsWithContext(ctx context.Context) *LoginGetParams {

	return &LoginGetParams{

		Context: ctx,
	}
}

// NewLoginGetParamsWithHTTPClient creates a new LoginGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoginGetParamsWithHTTPClient(client *http.Client) *LoginGetParams {

	return &LoginGetParams{
		HTTPClient: client,
	}
}

/*LoginGetParams contains all the parameters to send to the API endpoint
for the login get operation typically these are written to a http.Request
*/
type LoginGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the login get params
func (o *LoginGetParams) WithTimeout(timeout time.Duration) *LoginGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login get params
func (o *LoginGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login get params
func (o *LoginGetParams) WithContext(ctx context.Context) *LoginGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login get params
func (o *LoginGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login get params
func (o *LoginGetParams) WithHTTPClient(client *http.Client) *LoginGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login get params
func (o *LoginGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LoginGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
