// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// LoginPostReader is a Reader for the LoginPost structure.
type LoginPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoginPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLoginPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewLoginPostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLoginPostOK creates a LoginPostOK with default headers values
func NewLoginPostOK() *LoginPostOK {
	return &LoginPostOK{}
}

/*LoginPostOK handles this case with default header values.

Token response
*/
type LoginPostOK struct {
	Payload *models.Token
}

func (o *LoginPostOK) Error() string {
	return fmt.Sprintf("[POST /login][%d] loginPostOK  %+v", 200, o.Payload)
}

func (o *LoginPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Token)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginPostDefault creates a LoginPostDefault with default headers values
func NewLoginPostDefault(code int) *LoginPostDefault {
	return &LoginPostDefault{
		_statusCode: code,
	}
}

/*LoginPostDefault handles this case with default header values.

Error response
*/
type LoginPostDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the login post default response
func (o *LoginPostDefault) Code() int {
	return o._statusCode
}

func (o *LoginPostDefault) Error() string {
	return fmt.Sprintf("[POST /login][%d] LoginPost default  %+v", o._statusCode, o.Payload)
}

func (o *LoginPostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
