// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// RefreshGetReader is a Reader for the RefreshGet structure.
type RefreshGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RefreshGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRefreshGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRefreshGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRefreshGetOK creates a RefreshGetOK with default headers values
func NewRefreshGetOK() *RefreshGetOK {
	return &RefreshGetOK{}
}

/*RefreshGetOK handles this case with default header values.

Token response
*/
type RefreshGetOK struct {
	Payload *models.Token
}

func (o *RefreshGetOK) Error() string {
	return fmt.Sprintf("[GET /refresh][%d] refreshGetOK  %+v", 200, o.Payload)
}

func (o *RefreshGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Token)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRefreshGetDefault creates a RefreshGetDefault with default headers values
func NewRefreshGetDefault(code int) *RefreshGetDefault {
	return &RefreshGetDefault{
		_statusCode: code,
	}
}

/*RefreshGetDefault handles this case with default header values.

Error response
*/
type RefreshGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the refresh get default response
func (o *RefreshGetDefault) Code() int {
	return o._statusCode
}

func (o *RefreshGetDefault) Error() string {
	return fmt.Sprintf("[GET /refresh][%d] RefreshGet default  %+v", o._statusCode, o.Payload)
}

func (o *RefreshGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
