// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ecadlabs/auth-client/models"
)

// LogsGetReader is a Reader for the LogsGet structure.
type LogsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewLogsGetNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewLogsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLogsGetNoContent creates a LogsGetNoContent with default headers values
func NewLogsGetNoContent() *LogsGetNoContent {
	return &LogsGetNoContent{}
}

/*LogsGetNoContent handles this case with default header values.

Log data
*/
type LogsGetNoContent struct {
	Payload *models.LogsResponse
}

func (o *LogsGetNoContent) Error() string {
	return fmt.Sprintf("[GET /logs/][%d] logsGetNoContent  %+v", 204, o.Payload)
}

func (o *LogsGetNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LogsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogsGetDefault creates a LogsGetDefault with default headers values
func NewLogsGetDefault(code int) *LogsGetDefault {
	return &LogsGetDefault{
		_statusCode: code,
	}
}

/*LogsGetDefault handles this case with default header values.

Error response
*/
type LogsGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the logs get default response
func (o *LogsGetDefault) Code() int {
	return o._statusCode
}

func (o *LogsGetDefault) Error() string {
	return fmt.Sprintf("[GET /logs/][%d] LogsGet default  %+v", o._statusCode, o.Payload)
}

func (o *LogsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
