// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Predicate Predicate
// swagger:model Predicate
type Predicate struct {

	// Equal
	Eq string `json:"eq,omitempty"`

	// Greater or equal
	Ge string `json:"ge,omitempty"`

	// Greater than
	Gt string `json:"gt,omitempty"`

	// Collection contains value
	Has string `json:"has,omitempty"`

	// SQL LIKE
	L string `json:"l,omitempty"`

	// Less or equal
	Le string `json:"le,omitempty"`

	// Less than
	Lt string `json:"lt,omitempty"`

	// Not equal
	Ne string `json:"ne,omitempty"`

	// Has prefix
	P string `json:"p,omitempty"`

	// POSIX Regex
	Re string `json:"re,omitempty"`

	// Has suffix
	S string `json:"s,omitempty"`

	// Has substring
	Sub string `json:"sub,omitempty"`
}

// Validate validates this predicate
func (m *Predicate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Predicate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Predicate) UnmarshalBinary(b []byte) error {
	var res Predicate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
